dist: trusty
sudo: false
language: java
before_install:
  - ulimit -c unlimited -S
script:
  - ./mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvn test -B
  - ./mvn site -pl docs -B
cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
