dist: trusty
sudo: false
language: java
before_install:
  - ulimit -c unlimited -S
cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
