#server configurations
server:
  applicationConnectors:
    - type: http
      port: 8080



#database configurations
database:
  driverClass: org.postgresql.Driver
  user: siem1701
  password: beabea
  url: jdbc:postgresql://db.fe.up.pt:5432/siem1701?currentSchema=foodback


logging:
  level: INFO
  loggers:
    com.lpro: DEBUG
