#server configurations
server:
  applicationConnectors:
    - type: http
      port: 3000



#database configurations
database:
  driverClass: org.postgresql.Driver
  user: sibd17g21
  password: batatinhas
  url: jdbc:postgresql://dbm.fe.up.pt:5432/sibd17g21?currentSchema=test


logging:
  level: INFO
  loggers:
    com.lpro: DEBUG
